# Generated by Django 4.1.7 on 2023-03-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="account",
            name="last_name",
        ),
        migrations.AddField(
            model_name="account",
            name="full_name",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
