# Generated by Django 4.1.7 on 2023-03-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_remove_account_first_name_remove_account_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="password",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
