# Generated by Django 4.1.7 on 2023-03-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_account_saldo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Balance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saldo", models.IntegerField(default=0)),
                ("saved_money", models.IntegerField(default=0)),
                ("money_applied", models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name="account",
            name="saldo",
        ),
    ]
