# Generated by Django 4.1.7 on 2023-03-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0008_balance_cpf_alter_balance_money_applied_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="card",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
