# Generated by Django 4.1.7 on 2023-03-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0010_card_type_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="type_card",
            field=models.CharField(
                choices=[("gl", "Gold"), ("pt", "Platinum"), ("dm", "Diamond")],
                default="gl",
                max_length=2,
            ),
        ),
    ]
