# Generated by Django 4.1.7 on 2023-03-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0011_alter_card_type_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balance",
            name="money_applied",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="balance",
            name="saldo",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="balance",
            name="saved_money",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
