# Generated by Django 4.1.7 on 2023-03-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0013_transactionhistory_transactiontarget_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionhistory",
            name="message",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
