# Generated by Django 4.1.7 on 2023-03-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0016_transactionhistory_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="fcmtoken",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
