# Generated by Django 4.1.7 on 2023-03-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0017_account_fcmtoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="fcmtoken",
        ),
        migrations.AddField(
            model_name="account",
            name="pushtoken",
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
